version: 0.2

phases:
  install:
    testvar1: "testvar1 value"
    pwd: $(echo hello)
    commands:
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
      - pip install boto3

  pre_build:
    commands:
      - echo testvar1 $testvar1
      - echo pwd $pwd
      - echo awsregion $AWS_REGION
      - aws ec2 describe-subnets --filters "Name=vpc-id,Values=<vpc-id>" --region $AWS_REGION
      - python ./getPubSubnets.py --vpcid vpc-02eb0955c61a7c779
      # Discover and run unit tests in the 'tests' directory. For more information, see <https://docs.python.org/3/library/unittest.html#test-discovery>
      - python -m unittest discover tests
  
  build:
    commands:

      # Use AWS SAM to package the application by using AWS CloudFormation
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml

artifacts:
  type: zip
  files:
    - template-export.yml